[TOKENS]
bot = ""

# 50 = CRITICAL
# 40 = ERROR
# 30 = WARNING
# 20 = INFO
# 10 = DEBUG
[LOGGING]
level = 20

[DATABASE]
dsn = "postgres://user:password@localhost:5432/database"

[DDRAGON]
webhook = "WEBHOOK_URL"